export enum MessageTypes {
  NOTIFICATION_COUNT_UPDATED = "NOTIFICATION_COUNT_UPDATED",
  GET_NOTIFICATIONS = "GET_NOTIFICATIONS",
  UPDATE_NOTIFICATION_READ_STATUS = "UPDATE_NOTIFICATION_READ_STATUS",
  UPDATE_USER_DATA_IN_SHELL = "UPDATE_USER_DATA_IN_SHELL",
}
